name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
    runs-on: ubuntu-latest
    name: 'Tarea para saludar'
    steps:
      - name: 'Ejecutar la accion de Docker'
        id: hola
        uses: docker_Jueves_Luis/accion@v1
        with:
          quien: 'Lucho'
      - name: 'Mostra la hora obtenida'
        run: echo "La hora obtenida fue ${{ steps.hola.outputs.hora }}"
